#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Insira um argumento válido: log-archive [diretório]"
  exit 1
fi

dir="$1"

time=$(date +%Y%m%d_%H%M%S)
filename="logs_archive_${time}.tar.gz"

echo "Compactando o diretório $dir"

tar --ignore-failed-read -czf "$filename" "$dir" 2>/dev/null

echo "Arquivo criado: $filename"
echo "Concluído"
