#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Insira um argumento válido: log-archive [diretório]"
  exit 1
fi

dir="$1"

time=$(date +%Y%m%d_%H%M%S)
filename="logs_archive_${time}.tar.gz"

echo "Compactando o diretório $dir"

stderr=$(tar --ignore-failed-read -czf "$filename" "$dir" 2>&1 >/dev/null)

if [ -n "$stderr" ]; then
  echo "Aviso: alguns arquivos foram ignorados por falta de permissão"
fi

echo "Arquivo criado: $filename"
echo "Concluído"
