#!/usr/bin/env bash

CYAN='\033[0;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ -z "$1" ]; then
  echo -e "${RED}ERROR:${NC} Please provide a valid argument: log-archive [directory]"
  exit 1
fi

dir="$1"

time=$(date +%Y%m%d_%H%M%S)
filename="logs_archive_${time}.tar.gz"

echo -e "${CYAN}Compressing:${NC} $dir"

stderr=$(tar --ignore-failed-read -czf "$filename" "$dir" 2>&1 >/dev/null)

if [ -n "$stderr" ]; then
  echo -e "${YELLOW}Warning:${NC} some files were skipped due to permission denied"
fi

echo -e "${GREEN}Success:${NC} Archive created: $filename"
